package testcxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-10T23:38:52.394+08:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "calculator",
                  wsdlLocation = "http://localhost:8080/calculator?wsdl",
                  targetNamespace = "http://testCXF/")
public class Calculator extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://testCXF/", "calculator");
    public final static QName CalculatorServiceImplPort = new QName("http://testCXF/", "CalculatorServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/calculator?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Calculator.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/calculator?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Calculator(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Calculator(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Calculator() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Calculator(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Calculator(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Calculator(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServiceImplPort")
    public CalculatorService getCalculatorServiceImplPort() {
        return super.getPort(CalculatorServiceImplPort, CalculatorService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServiceImplPort")
    public CalculatorService getCalculatorServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CalculatorServiceImplPort, CalculatorService.class, features);
    }

}
