package testcxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-10T23:38:52.338+08:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://testCXF/", name = "CalculatorService")
@XmlSeeAlso({ObjectFactory.class})
public interface CalculatorService {

    @WebMethod
    @Action(input = "http://testCXF/CalculatorService/addRequest", output = "http://testCXF/CalculatorService/addResponse")
    @RequestWrapper(localName = "add", targetNamespace = "http://testCXF/", className = "testcxf.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://testCXF/", className = "testcxf.AddResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int add(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1
    );

    @WebMethod
    @Action(input = "http://testCXF/CalculatorService/concatRequest", output = "http://testCXF/CalculatorService/concatResponse")
    @RequestWrapper(localName = "concat", targetNamespace = "http://testCXF/", className = "testcxf.Concat")
    @ResponseWrapper(localName = "concatResponse", targetNamespace = "http://testCXF/", className = "testcxf.ConcatResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String concat(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );
}
